### ISSUE TITLE
DevOps Roadmap

### ISSUE THREAD

**Issue by guilyx** [APLA-Toolbox/pymapf#2]
- [x] Upload package on Pypi
    - [x] Create setup.py
    - [x] Find a name
    - [x] Tag version
- [x] Setup Github Actions
    - [x] Build from repo
    - [x] Test from repo
    - [x] Build from pypi
- [x] Setup Contributing.md
- [x] Setup issue templates
- [x] Setup PR templates
